spring.application.name=edumis

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/edumis
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
